version: "3.8"

services:
  product-db:
    image: postgres:15
    container_name: product-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
    volumes:
      - ./database/product_pgdata:/var/lib/postgresql/data
  user-db:
    image: postgres:15
    container_name: user-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5436:5432"
    volumes:
      - ./database/user_pgdata:/var/lib/postgresql/data
  inventory-db:
    image: postgres:15
    container_name: inventory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5437:5432"
    volumes:
      - ./database/inventory_pgdata:/var/lib/postgresql/data

  kafka:
    image: wurstmeister/kafka
    container_name: microsvc-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      TOPIC_AUTO_CREATE: "false"
      DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: microsvc-zookeeper
    ports:
      - "2181:2181"
